config/routes.rb
Rails.application.routes.draw do

  get 'worker_invoice/invoiced'

  get 'doctor_appoint/ready'

  get 'admin_done/doned'

  get 'admin_appointment/completed'

  get 'patient_appointment/edit'

  resources :appointment_conditions

  resources :time_slots

  resources :appointments

  resources :timeslots

  resources :appointment_statuses

  resources :diagnoses

  resources :doctors

  resources :patients

  get 'worker_invoice/geninvoice'

  get 'doctor_appointment/docsession'

  get 'admin_edit_db/editdatabase'

  get 'worker_dashboard/workerdash'

  get 'doctor_dashboard/doctordash'

  get 'patient_dashboard/patientdash'

  get 'admin_dashboard/admindash'

  get 'sysadmin/admin'

  get 'dashboard/dash'

  get 'controllername/new'

  get 'controllername/create'

  get 'admin_done/doned'

   root 'dashboard#dash'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  #has_many :patients
 # has_many :doctors
 # has_many :time_slots
  #has_many :diagnosises
 # has_many :appointment_conditions
  belongs_to :patient
  belongs_to :doctor
  belongs_to :time_slot
  belongs_to :diagnosis
  belongs_to :appointment_condition


  validates_uniqueness_of :doctor_id, scope: [:time_slot_id, :visit_date], :message=>"Appointment booked, please select different time and/or doctor"

  validates_presence_of :patient_id
  validates_presence_of :doctor_id
  validates_presence_of :time_slot_id
  validates_presence_of :diagnosis_id
  validates_presence_of :appointment_condition_id

  validate :future
  validate :not_weekend
  before_destroy :ateHrs

  def future
    if Date.today >= self.visit_date
    errors.add :visit_date, "You must select date after today"
    end
  end


  def not_weekend
    if visit_date.saturday? == true or visit_date.sunday? == true
      errors.add :visit_date, ': Dermo is closed on weekends, call 911 for emergency'
      return false
    end
  end

  def ateHrs
      if (time_slot.time_time - Time.now) < 8
      errors.add :base, "You must call front desk at 832-949-9867 to cancel or reschedule if 8 hours before appointment"
      return false
      end
  end
  def self.appointmentNew
    Appointment.where("appointment_condition_id =?", 1)
  end
  def self.appointmentDone
    Appointment.where("appointment_condition_id =?", 2)
  end



  def self.patient_create
    @appointment = Appointment.new
    end



end

app/models/appointment_condition.rb
class AppointmentCondition < ActiveRecord::Base
  has_many :appointments
 # belongs_to :appointment

  validates_presence_of :current_status
end

app/models/diagnosis.rb
class Diagnosis < ActiveRecord::Base
  has_many :appointments
  #belongs_to :appointment

  validates_presence_of :code
  validates_presence_of :description
  validates_presence_of :price

  def diagcode
    code + ': ' + description
  end
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
 has_many :appointments
  #belongs_to :appointment
  has_many :patients, through: :appointments

  validates_presence_of :dfirst_name
  validates_presence_of :dlast_name


  def full_name
    "#{dlast_name}, #{dfirst_name}"
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
 has_many :appointments
  #belongs_to :appointment
  has_many :doctors, :through => :appointments
  has_many :time_slots, :through => :appointments
 has_many :diagnosises, :through => :appointments

  validates_presence_of :first_name
  validates_presence_of :last_name





  def full_name
    "#{last_name}, #{first_name}"
  end

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments

  validates_presence_of :time_time
  validates_presence_of :time_name

end

app/controllers/worker_invoice_controller.rb
class WorkerInvoiceController < ApplicationController
  def invoiced
    @appointments = Appointment.appointmentDone
  end
end

app/helpers/admin_complete_helper.rb
module AdminCompleteHelper
end

app/helpers/admin_done_helper.rb
module AdminDoneHelper
end

app/helpers/admin_edit_db_helper.rb
module AdminEditDbHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/controllername_helper.rb
module ControllernameHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patient_find_helper.rb
module PatientFindHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sysadmin_helper.rb
module SysadminHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/helpers/worker_invoice_helper.rb
module WorkerInvoiceHelper
end

app/views/worker_invoice/invoiced.html.erb
<style type="text/css">
    .tftable {font-size:12px;color:#333333;width:100%;border-width: 1px;border-color: #3B5A8C;border-collapse: collapse;}
    .tftable th {font-size:12px;background-color:#007dc1
    ;border-width: 1px;padding: 8px;border-style: solid;border-color: #3B5A8C;text-align:left;}
    .tftable tr {background-color:#d7e1ee;}
    .tftable td {font-size:12px;border-width: 1px;padding: 8px;border-style: solid;border-color: #3B5A8C;}
    .tftable tr:hover {background-color:#ffff99;}
</style>


<h1 class="centered">Invoices</h1>

<%= button_to 'Home', dashboard_dash_path, :class => 'myButton side buttonseperate', :method => :get%>
<%= button_to 'Dashboard', worker_dashboard_workerdash_path, :class => 'myButton side buttonseperate', :method => :get%>
<br>
<br>
<br>
<table class="tftable" border="1">
  <thead>
  <tr>
    <th>
      Invoice Number
    </th>
    <th>
      Doctor Name
    </th>
    <th>
      Patient Name
    </th>
    <th>
      Appointment Date
    </th>
    <th>
      Time
    </th>
    <th>
      Diagnosis
    </th>
    <th>
      Diagnosis Amount
    </th>
    <th>
      Appointment Fee
    </th>
    <th>
      Total Fee
    </th>
  </tr>
  </thead>
  <% @appointments.each do |appointment| %>
      <tr>
        <td>
         <%= (rand() * 5000).to_i %>
        </td>
        <td>
          <%= appointment.doctor.full_name %>
        </td>
        <td>
          <%= appointment.patient.full_name %>
        </td>
        <td>
          <%= appointment.visit_date %>
        </td>
        <td>
          <%= appointment.time_slot.time_name %>
        </td>
        <td>
          <%= appointment.diagnosis.diagcode %>
        </td>
        <td>
          <%= number_to_currency(appointment.diagnosis.price) %>
        </td>
        <td>
          <%= number_to_currency(appointment.appointment_condition.charge_fee) %>
        </td>
        <td>
          <%=number_to_currency(appointment.diagnosis.price + appointment.appointment_condition.charge_fee) %>
        </td>
      </tr>
  <% end %>
</table>