config/routes.rb
Rails.application.routes.draw do

  get 'worker_invoice/invoiced'

  get 'doctor_appoint/ready'

  get 'admin_done/doned'

  get 'admin_appointment/completed'

  get 'patient_appointment/edit'

  resources :appointment_conditions

  resources :time_slots

  resources :appointments

  resources :timeslots

  resources :appointment_statuses

  resources :diagnoses

  resources :doctors

  resources :patients

  get 'worker_invoice/geninvoice'

  get 'doctor_appointment/docsession'

  get 'admin_edit_db/editdatabase'

  get 'worker_dashboard/workerdash'

  get 'doctor_dashboard/doctordash'

  get 'patient_dashboard/patientdash'

  get 'admin_dashboard/admindash'

  get 'sysadmin/admin'

  get 'dashboard/dash'

  get 'controllername/new'

  get 'controllername/create'

  get 'admin_done/doned'

   root 'dashboard#dash'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  #has_many :patients
 # has_many :doctors
 # has_many :time_slots
  #has_many :diagnosises
 # has_many :appointment_conditions
  belongs_to :patient
  belongs_to :doctor
  belongs_to :time_slot
  belongs_to :diagnosis
  belongs_to :appointment_condition


  validates_uniqueness_of :doctor_id, scope: [:time_slot_id, :visit_date], :message=>"Appointment booked, please select different time and/or doctor"

  validates_presence_of :patient_id
  validates_presence_of :doctor_id
  validates_presence_of :time_slot_id
  validates_presence_of :diagnosis_id
  validates_presence_of :appointment_condition_id

  validate :future
  validate :not_weekend
  before_destroy :ateHrs

  def future
    if Date.today >= self.visit_date
    errors.add :visit_date, "You must select date after today"
    end
  end


  def not_weekend
    if visit_date.saturday? == true or visit_date.sunday? == true
      errors.add :visit_date, ': Dermo is closed on weekends, call 911 for emergency'
      return false
    end
  end

  def ateHrs
      if (time_slot.time_time - Time.now) < 8
      errors.add :base, "You must call front desk at 832-949-9867 to cancel or reschedule if 8 hours before appointment"
      return false
      end
  end
  def self.appointmentNew
    Appointment.where("appointment_condition_id =?", 1)
  end
  def self.appointmentDone
    Appointment.where("appointment_condition_id =?", 2)
  end



  def self.patient_create
    @appointment = Appointment.new
    end



end

app/models/appointment_condition.rb
class AppointmentCondition < ActiveRecord::Base
  has_many :appointments
 # belongs_to :appointment

  validates_presence_of :current_status
end

app/models/diagnosis.rb
class Diagnosis < ActiveRecord::Base
  has_many :appointments
  #belongs_to :appointment

  validates_presence_of :code
  validates_presence_of :description
  validates_presence_of :price

  def diagcode
    code + ': ' + description
  end
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
 has_many :appointments
  #belongs_to :appointment
  has_many :patients, through: :appointments

  validates_presence_of :dfirst_name
  validates_presence_of :dlast_name


  def full_name
    "#{dlast_name}, #{dfirst_name}"
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
 has_many :appointments
  #belongs_to :appointment
  has_many :doctors, :through => :appointments
  has_many :time_slots, :through => :appointments
 has_many :diagnosises, :through => :appointments

  validates_presence_of :first_name
  validates_presence_of :last_name





  def full_name
    "#{last_name}, #{first_name}"
  end

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments

  validates_presence_of :time_time
  validates_presence_of :time_name

end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  before_action :set_diagnosis, only: [:show, :edit, :update, :destroy]

  # GET /diagnoses
  # GET /diagnoses.json
  def index
    @diagnoses = Diagnosis.all
  end

  # GET /diagnoses/1
  # GET /diagnoses/1.json
  def show
  end

  # GET /diagnoses/new
  def new
    @diagnosis = Diagnosis.new
  end

  # GET /diagnoses/1/edit
  def edit
  end

  # POST /diagnoses
  # POST /diagnoses.json
  def create
    @diagnosis = Diagnosis.new(diagnosis_params)

    respond_to do |format|
      if @diagnosis.save
        format.html { redirect_to @diagnosis, notice: 'Diagnosis was successfully created.' }
        format.json { render :show, status: :created, location: @diagnosis }
      else
        format.html { render :new }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnoses/1
  # PATCH/PUT /diagnoses/1.json
  def update
    respond_to do |format|
      if @diagnosis.update(diagnosis_params)
        format.html { redirect_to @diagnosis, notice: 'Diagnosis was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnosis }
      else
        format.html { render :edit }
        format.json { render json: @diagnosis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnoses/1
  # DELETE /diagnoses/1.json
  def destroy
    @diagnosis.destroy
    respond_to do |format|
      format.html { redirect_to diagnoses_url, notice: 'Diagnosis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnosis
      @diagnosis = Diagnosis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnosis_params
      params.require(:diagnosis).permit(:code, :description, :price)
    end
end

app/helpers/admin_complete_helper.rb
module AdminCompleteHelper
end

app/helpers/admin_done_helper.rb
module AdminDoneHelper
end

app/helpers/admin_edit_db_helper.rb
module AdminEditDbHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/controllername_helper.rb
module ControllernameHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/doctor_appoint_helper.rb
module DoctorAppointHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patient_find_helper.rb
module PatientFindHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sysadmin_helper.rb
module SysadminHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/diagnoses/_form.html.erb
<%= form_for(@diagnosis) do |f| %>
  <% if @diagnosis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnosis.errors.count, "error") %> prohibited this diagnosis from being saved:</h2>

      <ul>
      <% @diagnosis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnoses/edit.html.erb
<h1>Editing diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnosis %> |
<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/index.html.erb
<style type="text/css">
    .tftable {font-size:12px;color:#333333;width:100%;border-width: 1px;border-color: #3B5A8C;border-collapse: collapse;}
    .tftable th {font-size:12px;background-color:#007dc1
    ;border-width: 1px;padding: 8px;border-style: solid;border-color: #3B5A8C;text-align:left;}
    .tftable tr {background-color:#d7e1ee;}
    .tftable td {font-size:12px;border-width: 1px;padding: 8px;border-style: solid;border-color: #3B5A8C;}
    .tftable tr:hover {background-color:#ffff99;}
</style>

<h1>Listing diagnoses</h1>
<%= button_to 'Dashboard', admin_edit_db_editdatabase_path, :class => 'myButton', :method => :get%>
<table class="tftable" border="1">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diagnoses.each do |diagnosis| %>
      <tr>
        <td><%= diagnosis.code %></td>
        <td><%= diagnosis.description %></td>
        <td><%= diagnosis.price %></td>
        <td><%= link_to 'Show', diagnosis %></td>
        <td><%= link_to 'Edit', edit_diagnosis_path(diagnosis) %></td>
        <td><%= link_to 'Destroy', diagnosis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagnosis', new_diagnosis_path %>

app/views/diagnoses/new.html.erb
<h1>New diagnosis</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnoses_path %>

app/views/diagnoses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @diagnosis.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @diagnosis.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @diagnosis.price %>
</p>

<%= link_to 'Edit', edit_diagnosis_path(@diagnosis) %> |
<%= link_to 'Back', diagnoses_path %>