config/routes.rb
Rails.application.routes.draw do

  get 'worker_invoice/invoiced'

  get 'doctor_appoint/ready'

  get 'admin_done/doned'

  get 'admin_appointment/completed'

  get 'patient_appointment/edit'

  resources :appointment_conditions

  resources :time_slots

  resources :appointments

  resources :timeslots

  resources :appointment_statuses

  resources :diagnoses

  resources :doctors

  resources :patients

  get 'worker_invoice/geninvoice'

  get 'doctor_appointment/docsession'

  get 'admin_edit_db/editdatabase'

  get 'worker_dashboard/workerdash'

  get 'doctor_dashboard/doctordash'

  get 'patient_dashboard/patientdash'

  get 'admin_dashboard/admindash'

  get 'sysadmin/admin'

  get 'dashboard/dash'

  get 'controllername/new'

  get 'controllername/create'

  get 'admin_done/doned'

   root 'dashboard#dash'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  #has_many :patients
 # has_many :doctors
 # has_many :time_slots
  #has_many :diagnosises
 # has_many :appointment_conditions
  belongs_to :patient
  belongs_to :doctor
  belongs_to :time_slot
  belongs_to :diagnosis
  belongs_to :appointment_condition


  validates_uniqueness_of :doctor_id, scope: [:time_slot_id, :visit_date], :message=>"Appointment booked, please select different time and/or doctor"

  validates_presence_of :patient_id
  validates_presence_of :doctor_id
  validates_presence_of :time_slot_id
  validates_presence_of :diagnosis_id
  validates_presence_of :appointment_condition_id

  validate :future
  validate :not_weekend
  before_destroy :ateHrs

  def future
    if Date.today >= self.visit_date
    errors.add :visit_date, "You must select date after today"
    end
  end


  def not_weekend
    if visit_date.saturday? == true or visit_date.sunday? == true
      errors.add :visit_date, ': Dermo is closed on weekends, call 911 for emergency'
      return false
    end
  end

  def ateHrs
      if (time_slot.time_time - Time.now) < 8
      errors.add :base, "You must call front desk at 832-949-9867 to cancel or reschedule if 8 hours before appointment"
      return false
      end
  end
  def self.appointmentNew
    Appointment.where("appointment_condition_id =?", 1)
  end
  def self.appointmentDone
    Appointment.where("appointment_condition_id =?", 2)
  end



  def self.patient_create
    @appointment = Appointment.new
    end



end

app/models/appointment_condition.rb
class AppointmentCondition < ActiveRecord::Base
  has_many :appointments
 # belongs_to :appointment

  validates_presence_of :current_status
end

app/models/diagnosis.rb
class Diagnosis < ActiveRecord::Base
  has_many :appointments
  #belongs_to :appointment

  validates_presence_of :code
  validates_presence_of :description
  validates_presence_of :price

  def diagcode
    code + ': ' + description
  end
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
 has_many :appointments
  #belongs_to :appointment
  has_many :patients, through: :appointments

  validates_presence_of :dfirst_name
  validates_presence_of :dlast_name


  def full_name
    "#{dlast_name}, #{dfirst_name}"
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
 has_many :appointments
  #belongs_to :appointment
  has_many :doctors, :through => :appointments
  has_many :time_slots, :through => :appointments
 has_many :diagnosises, :through => :appointments

  validates_presence_of :first_name
  validates_presence_of :last_name





  def full_name
    "#{last_name}, #{first_name}"
  end

end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base
  has_many :appointments

  validates_presence_of :time_time
  validates_presence_of :time_name

end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.require(:time_slot).permit(:time_name)
    end
end

app/helpers/admin_complete_helper.rb
module AdminCompleteHelper
end

app/helpers/admin_done_helper.rb
module AdminDoneHelper
end

app/helpers/admin_edit_db_helper.rb
module AdminEditDbHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/controllername_helper.rb
module ControllernameHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/doctor_appoint_helper.rb
module DoctorAppointHelper
end

app/helpers/doctor_session_helper.rb
module DoctorSessionHelper
  @appointments = Appointment.all
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patient_create_helper.rb
module PatientCreateHelper
end

app/helpers/patient_find_helper.rb
module PatientFindHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sysadmin_helper.rb
module SysadminHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_for(@time_slot) do |f| %>
  <% if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% @time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_name %><br>
    <%= f.text_field :time_name %>
  </div>
  <div class="field">
    <%= f.label :time_time %><br>
    <%= f.time_select :time_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing time_slot</h1>
<%= button_to 'Dashboard', admin_edit_db_editdatabase_path, :class => 'myButton', :method => :get%>
<%= render 'form' %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<style type="text/css">
    .tftable {font-size:12px;color:#333333;width:100%;border-width: 1px;border-color: #3B5A8C;border-collapse: collapse;}
    .tftable th {font-size:12px;background-color:#007dc1
    ;border-width: 1px;padding: 8px;border-style: solid;border-color: #3B5A8C;text-align:left;}
    .tftable tr {background-color:#d7e1ee;}
    .tftable td {font-size:12px;border-width: 1px;padding: 8px;border-style: solid;border-color: #3B5A8C;}
    .tftable tr:hover {background-color:#ffff99;}
</style>

<h1>Listing time_slots</h1>

<table class="tftable" border="1">
  <thead>
    <tr>
      <th>Time name</th>
      <th>Time time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.time_name %></td>
        <td><%= time_slot.time_time %></td>
        <td><%= link_to 'Show', time_slot %></td>
        <td><%= link_to 'Edit', edit_time_slot_path(time_slot) %></td>
        <td><%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time slot', new_time_slot_path %>

app/views/time_slots/new.html.erb
<h1>New time_slot</h1>

<%= render 'form' %>

<%= link_to 'Back', time_slots_path %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time name:</strong>
  <%= @time_slot.time_name %>
</p>

<p>
  <strong>Time time:</strong>
  <%= @time_slot.time_time %>
</p>

<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>